import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from "react";
import "./global.css"
import NavBar from "../components/NavBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={`md:text-3xl antialiased max-w-2xl mb-40 mt-8 lg:mx-auto ${inter.className}`}>
      <NavBar/>
      {children}
      </body>
    </html>
  )
}
